services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/bootstrap.php'

  App\LoadBalancer\LoadBalancerInterface:
    class: App\LoadBalancer\RoundRobinLoadBalancer
    arguments:
      $servers: '%app.backend.servers%'

  App\Server\ServerInterface:
    class: App\Server\HttpServer
    public: true
    arguments:
      $host: '%app.server.host%'
      $port: '%app.server.port%'

parameters:
  app.server.host: '0.0.0.0'
  app.server.port: 9501
  app.backend.servers:
    - 'http://localhost:8080'
    - 'http://localhost:8081'
    - 'http://localhost:8082'